### ISSUE TITLE
Avoid failure if no sources with release-version.sh

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-scripts#13]
When using `release-version.sh` in projects without attached sources, the script "fails" - but at that point the core artifact has already been uploaded. So maybe execution should just continue?

If we want jobs without sources to fail, the check should come beforehand (e.g. with an enforcer plugin)

**Comment by ctrueden** [comment]
I don't remember which project(s) this issue would even to be addressed. And the script has substantially changed now, leveraging Travis CI to do the actual deployment now. So I'll close this issue; we can reopen if it comes up again.
