### ISSUE TITLE
Releasing with release-version.sh stops halfway with Git Bash on Windows

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-scripts#17]
When having unstashed/uncommited changes in the working copy of a repository and running `release-version.sh`, it proceeds to create a tag but then leaves you with a 'detached HEAD' state without finalizing the release.

UPDATE: this might be unrelated to the changes, it also left me halfway through the process when starting with a clean state. So this might rather be related to me using Git Bash on Windows...

**Comment by imagejan** [comment]
Sorry, this was a false alarm: for some reason (likely because I used one of Github's suggestions when first setting up the repository), I had `release.properties` in my `.gitignore` file, which blocked the release.

The commit https://github.com/fmi-faim/fmi-ij2-plugins/commit/675653ee7a24c2e134b33396ad992a41a63a6e29 fixed this, so I'm closing this issue.

@ctrueden what do you think, should we add a sanity check to `release-version.sh` to detect if some required files are ignored in the local git repo?

**Comment by ctrueden** [comment]
> should we add a sanity check to release-version.sh to detect if some required files are ignored in the local git repo?

Good idea; I added a `-f` to the `git add`, so that even if `release.properties` is in the `.gitignore`, it will still be added no matter what.
