### ISSUE TITLE
Consider japi-tracker integration into CI

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-scripts#27]
Consider integration of [`japi-tracker`](https://github.com/lvc/japi-tracker) in continuous integration to monitor the API state of all components managed on the SciJava/ImageJ maven repository. The reports could be hosted as static webpages similar to the javadoc, e.g. at `api-history.scijava.org` or some such.

For libraries released to Maven Central, the reports exist here:
* https://abi-laboratory.pro/java/tracker/timeline/scijava-common/
* https://abi-laboratory.pro/java/tracker/timeline/imglib2/

**Comment by imagejan** [comment]
.. or [`revapi`](https://github.com/revapi/revapi), as suggested by @ctrueden [on the forum](https://forum.image.sc/t/contains-interface-of-imglib2-roi-is-gone/22912/19?u=imagejan).

**Comment by imagejan** [comment]
Happy to see that @frauzufall and @ctrueden seem to be working on something similar at the KNIME hackathon :slightly_smiling_face:
https://gitter.im/knime-ip/hackathon-KNIME-2019?at=5d8739ebab4244767be45619

**Comment by frauzufall** [comment]
Oh cool! On a first view the reports linked above look way better than what I tried.

**Comment by ctrueden** [comment]
Ah, thanks @imagejan, I had forgotten all about this. Sorry about that, @frauzufall.

**Comment by frauzufall** [comment]
This might be simpler to integrate e.g. into the release script: https://revapi.org/modules/revapi-maven-plugin/

**Comment by imagejan** [comment]
`revapi-maven-plugin` looks great!

I suggest adding a section like this to `<pluginManagement>` in `pom-scijava` (or `pom-scijava-base`?):

```
			<plugin>
				<groupId>org.revapi</groupId>
				<artifactId>revapi-maven-plugin</artifactId>
				<version>0.11.4</version>
				<dependencies>
					<dependency>
						<groupId>org.revapi</groupId>
						<artifactId>revapi-java</artifactId>
						<version>0.20.2</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
