### ISSUE TITLE
Automate generation of release notes

### ISSUE THREAD

**Issue by hanslovsky** [scijava/scijava-scripts#30]
Quoting myself from the [`scijava-common` gitter channel](https://gitter.im/scijava/scijava-common?at=5d387060ec5abe7bbc3e9637):

I have been thinking of how to automate release notes management to some extent. At the moment, at every release I go through all commits and try to find bug fixes/new features/(interface breaking changes), e.g:
https://github.com/saalfeldlab/paintera/releases

This is, of course, unreliable because I may forget to do that or it can be hard to find all relevant contributions when there were many commits between releases. Instead I thought that maybe there could be a release-notes.md in the repository with all previous releases and a current release note. Every pull request would need to modify the current release note appropriately and after a release, the current release note could just simply be copied into the release note/tag for that version.

This would simplify the process of figuring out what changes happened for a PR and I think this could even be automated with the scijava-scripts: The content of the current release note could be attached to the tag automatically and the suggested release version could be inferred from the contents of the release note itself. In that case it may be better to use something like xml/json/yaml instead of md for the current release note. I know of [`jq`](https://stedolan.github.io/jq/) as a very good json parser, so maybe json is the best choice here. I personally like yaml best for this use case but I don't think there is a good bash tool.

This is just something that came to my mind and there's probably some flaws but I would love to improve (gathering) release notes and ideally automate the process.

**Comment by hadim** [comment]
I like the idea of the PRs that needs to modify a release-notes.md file. A check could be added to Travis to raise an error if it's not the case.

And raising an error could be an option specified on Travis with a env variable such as `RAISE_ERROR_ON_RELEASE_NOTE`. So not every project would have to do that.

**Comment by hanslovsky** [comment]
@frauzufall [shared](https://gitter.im/scijava/scijava-common?at=5d49df9ed7fc9547500f7ec1) her [experiments with (automated) changelogs](https://github.com/juglab/versioning_fiji/blob/master/src/test/java/sc/fiji/versioning/ChangelogTest.java). 

Once there is a thread in the forum we should migrate the discussion there.

**Comment by hanslovsky** [comment]
There is a [forum thread](https://forum.image.sc/t/changelogs-release-notes-for-imagej-fiji-scijava-friends/28466) now and I will close this issue.
