### ISSUE TITLE
Deal with github renaming the default branch from master to main

### ISSUE THREAD

**Issue by tpietzsch** [scijava/scijava-scripts#36]
For newly created repositories, github names the default branch "main" by default now.

travisify.sh, release-version.sh, and others(?) hvae to be updated to work on both "master" and "main"

**Comment by ctrueden** [comment]
The travisify script was fixed by @imagejan with #38. The release-version script was fixed by me with a51f89417591fcd389e0f8ea095d6358567411b8.

There are still a few places in other scripts where `master` is hardcoded, so I'll leave this open for now.

**Comment by ctrueden** [comment]
The only places where `master` are still hardcoded are git-hg-synchronizer and travis-build, both of which are legacy scripts kept only for backwards compatibility. I may delete them at some point, since no core SciJava workflows rely on them anymore.
