### ISSUE TITLE
Workflow compatibility in scripts

### ISSUE THREAD

**Issue by kephale** [scijava/scijava-scripts#37]
We had a bit of a discussion about issues with the release-version.sh script on the sciview repo https://github.com/scenerygraphics/sciview/issues/322

This is just to link it over here and conclude a bit. I'd like to point out that it isn't that I necessarily have an issue with the recent changes to the script, but since there isn't any semvar versioning it isn't necessarily obvious to someone trying to naively use the scripts that an update would introduce so much extra work just to cut a release. This hurt a bit when I was trying to cut a release quickly for our I2K workshop and all of the licensing/git restrictions/etc. made it impossible. However, in all fairness, I had wonked other things in the process. 

I don't have any solutions to offer, or necessarily any observations of a specific problem. If we'd been releasing more often then this wouldn't have happened at a mission critical time. On the other hand, I don't love how much enforcement is happening by default, even if in the name of best practice.

**Comment by ctrueden** [comment]
Sorry for your pain, @kephale.

> all of the licensing/git restrictions/etc. made it impossible.

Would be nice to have more specific details why exactly it was "impossible" for you.

> I don't love how much enforcement is happening by default, even if in the name of best practice.

I respectfully disagree.
- Do all projects need a declared license? Yes, or else it is illegal to use them.
- Should all releases be reproducible from source? Yes, so the release script should verify there are no local changes.
Etc.

If there is a specific check you feel is inappropriate, by all means, let's discuss and find a solution. But a general "there is too much enforcement" is not constructive.

**Comment by kephale** [comment]
To be clear, I'm certain you know the right thing to do in terms of best practices here.

A more clear statement:
Being able to handle the changes in enforcement from scijava-scripts required significantly more time than I had anticipated. There is no semvar on this repository. I naively expected that if I updated the repo I would be able to repeat my normal workflow without obstacles. That wasn't the case, time was lost, we survived the workshop, but could have had a better performance. 

Again, no concrete action, you're being nice and puting up with me more than is needed. So I'll just quit complaining and figure out how to buffer these issues in the future.

**Comment by ctrueden** [comment]
> maybe next time there is a change, before it is strictly enforced it could come up as a (Y or n) option in the script.

Thanks for the idea. How about this?

Any time there is a new thing being enforced, if/when that check fails, the error message will clearly state which flag to pass to the script to skip that check. Would that be sufficient? I think I can promise to always give such hints in those cases!

**Comment by kephale** [comment]
That would definitely help, thank you

**Comment by ctrueden** [comment]
@kephale I added as many hints as I could for the existing checks, as well as a new `--skip-branch-check` flag if for some reason you need to release from a non-default branch:

https://github.com/scijava/scijava-scripts/compare/483b2cf48297546d76161805b22b4c0dbd96812a..8379c1fe9de7105b900479d8890fe17930b5560f

These patches also update the release script to work with default branches other than `master` and remotes other than `origin`.

Please let me know if there is anything else the script does that stymies you.
