### ISSUE TITLE
Refactor bump-POM-SciJava automation

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-scripts#4]
The logic for the current automation of bump-POM-SciJava via jenkins is distributed between [the jenkins job](http://jenkins.imagej.net/view/SciJava/job/Bump-POM-SciJava) itself and the [local script](https://github.com/scijava/scijava-scripts/blob/master/bump-pom-scijava.sh).

Instead, this logic should be entirely contained in shell scripts in this project.

Also, the current execution conflates two tasks:
1) Analyze the current pom-scijava to detect if it needs to be updated
2) Analyze downstream projects to see if their pom-scijava version needs to be updated

These tasks should be split into two separate scripts, the former calling the latter.

And finally, any transient information (such as e-mail addresses) should be discovered or input instead of being hard-coded.

**Comment by ctrueden** [comment]
The bump-versions-in-pom.sh script was retired earlier this year, along with the Bump-POM-SciJava Jenkins job. See also #5 and #8.
