### ISSUE TITLE
melting-pot: what to do about multi-module builds?

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-scripts#40]
When we create the mega-melt `pom.xml` we create a multi-module build where each dependency is a module.

If any of those dependencies are themselves modules of a multi-module build, where their aggregator is also their parent pom (i.e. https://github.com/axtimwalde/mpicbg), the now-orphaned modules appear to be unable to find their parents.

A heavy-handed suggestion: all child modules should include scijava repository blocks:

```
	<repositories>
		<repository>
			<id>scijava.public</id>
			<url>https://maven.scijava.org/content/groups/public</url>
		</repository>
	</repositories>
```

This way, the children will always know how to find their parents.

**Comment by hinerm** [comment]
@axtimwalde any feelings about this?

**Comment by axtimwalde** [comment]
Sure, anything you need me to do?
