### ISSUE TITLE
Melting-pot: Detecting incompatible bytecode

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-scripts#41]
The melting pot will currently not catch scenarios that do not involve API changes but require recompilation: for example, a change in generic parameters. This deficiency is due to the fact that we recompile each component before testing.

Some thoughts:
- For each project, compile the *test* sources only and run with the deployed `.jar`
- JPMS module versioning could be used as a way to indicate incompatibility, which presumably would be caught even if recompiling each project.
- [Rev API](https://revapi.org/revapi-site/index.html) might have some solutions?

**Comment by hinerm** [comment]
@tpietzsch let us know if you find anything interesting in rev api!

**Comment by ctrueden** [comment]
I am in favor of exploring revapi, to see what checks we can gain from that tool.

Setting revapi aside: to catch both binary and source imcompatibilities, I believe we would need two passes: one running the tests against the existing binary releases, and another after recompiling each component's code.

**Comment by ctrueden** [comment]
With f0b105ebbaefeb2e3a2692791fc307a4b3b44bc4, I added dual passes to the existing shell-based melting pot, which I believe resolves this issue.
