### ISSUE TITLE
release-version: newline style is fragile with WSL

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-scripts#47]
@imagejan wrote:
> When trying `release-properties.sh` from WSL terminal, I get:
> ```
> -bash: ../../scijava/scijava-scripts/release-version.sh: /bin/sh^M: bad interpreter: No such file or directory
> ```

Double check that this isn't an issue with newline style in the committed file.

**Comment by imagejan** [comment]
Indeed, this was an issue with a misconfiguration of git for Windows, checking out Windows-style line endings in a fresh installation. Sorry for the late follow-up.
